# Typhoon Impact Data Cleaning Notebook

This notebook focuses on preparing and cleaning the Typhoon Impacts Dataset, which contains information on flood-related impacts across different locations and time periods.

Typhoon impact data is often collected from multiple sources and across multiple years. As a result, the dataset may contain inconsistencies such as missing values, varying formats for dates and locations, duplicated records, or differences in how variables are recorded. These issues can affect the accuracy of analysis if they are not addressed during preprocessing.

To resolve these issues, this notebook performs several data cleaning tasks, including:

- Combining flood impact records from multiple years into a single consolidated dataset  
- Standardizing variable names and formats to maintain consistency across datasets  
- Handling missing or incomplete values where necessary  
- Ensuring that location and temporal variables follow a consistent structure  
- Verifying that numerical fields are stored in the correct data types  

By the end of this notebook, the dataset will be cleaned, standardized, and ready for further analysis, visualization, and modeling.

### Import
Start by importing **numpy**, **pandas**, and **glob**.

In [1]:
# Import relevant python modules
import numpy as np
import pandas as pd
import glob

## Step 1: Combine yearly CSVs

Merge the typhoon impact files (shared columns) into one dataframe, as it'd be easier to work on them all in one df.

### Locating the Typhoon Impact Dataset Files

In this step, we identify and collect the file paths of all CSV files that contain the typhoon or flood impact data. Instead of loading each dataset manually, we use Python's `glob` module to automatically locate all files that match a specific pattern within a folder.

In [2]:
# 1. Path to your folder containing the CSVs
path = '../data/typhoon-impact/*.csv'
all_files = glob.glob(path)

### Loading Multiple CSV Files into DataFrames

In this step, all the CSV files identified in the previous step are loaded into memory using a list comprehension. This approach allows multiple datasets to be read efficiently in a single line of code. After running, the variable **li** contains a list of DataFrames, each representing one of the CSV files. These DataFrames can then be combined or further processed in the subsequent steps of the data cleaning workflow.

In [3]:
# 2. Use a list comprehension to read them all at once
li = [pd.read_csv(filename) for filename in all_files]

### Combining the Datasets into a Single DataFrame

After loading the individual CSV files into a list of DataFrames, the next step is to combine them into one unified dataset. This is done using the `pd.concat()` function, which merges multiple DataFrames together. At the end of this step, all records from the separate CSV files are consolidated into a single master dataset that can be cleaned and analyzed more efficiently.

In [4]:
# 3. Concatenate them into one master DataFrame
df = pd.concat(li, axis=0, ignore_index=True)
df_clean = df.copy()

## Step 2: Quick data checks

Inspect shape, sample rows, dtypes, and missing values.

In [5]:
df.shape

(531, 13)

In [6]:
df.head()

,Cyclone Name,Region,Province,Deaths,Injuries,Affected,Houses destroyed,Houses damaged,Total Houses,Damage to Infrastructure (PhP),Damage to Agriculture + Fisheries (PhP),Year,Category
0,Amang,NaN,Agusan del Sur,0,NaN,10344.0,0.0,0,0,0.0,0.0,2019,Tropical depression
1,Amang,NaN,Surigao del Norte,0,NaN,3458.0,0.0,0,0,0.0,0.0,2019,Tropical depression
2,Amang,NaN,Agusan del Norte,0,NaN,1442.0,0.0,0,0,0.0,0.0,2019,Tropical depression
3,Amang,NaN,Surigao del Sur,0,NaN,853.0,0.0,0,0,0.0,0.0,2019,Tropical depression
4,Amang,NaN,Dinagat Islands,0,NaN,477.0,0.0,0,0,0.0,0.0,2019,Tropical depression

In [7]:
df.sample(10)

,Cyclone Name,Region,Province,Deaths,Injuries,Affected,Houses destroyed,Houses damaged,Total Houses,Damage to Infrastructure (PhP),Damage to Agriculture + Fisheries (PhP),Year,Category
271,Odette,Region 6,NaN,54,0.0,57866.0,18.0,3749,3767,0.0,2.771876e+09,2021,Super Typhoon
526,Verbena,Region 7,NaN,0,0.0,32308.0,4.0,204,208,0.0,0.000000e+00,2025,Tropical Depression
334,Betty,Region 1,NaN,0,0.0,4917.0,1.0,10,11,0.0,1.080000e+05,2023,Super Typhoon
521,Uwan,CAR,NaN,0,0.0,0.0,0.0,0,0,0.0,0.000000e+00,2025,Super Typhoon
248,Jolina,NCR,NaN,0,0.0,247.0,0.0,0,0,0.0,0.000000e+00,2021,Typhoon
380,Aghon,Region 7,NaN,0,0.0,629.0,0.0,0,0,0.0,0.000000e+00,2024,Typhoon
84,Ambo,NaN,Benguet,0,NaN,132.0,0.0,0,0,0.0,0.000000e+00,2020,Very strong typhoon
163,Ulysses,NaN,Cavite,3,NaN,14881.0,0.0,0,0,532460000.0,4.369846e+07,2020,Very strong typhoon
83,Ambo,NaN,Samar,0,NaN,5861.0,18.0,1353,1371,0.0,2.015300e+06,2020,Very strong typhoon
116,Quinta,NaN,Metro Manila,0,NaN,0.0,0.0,0,0,0.0,0.000000e+00,2020,Very strong typhoon

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 531 entries, 0 to 530
Data columns (total 13 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Cyclone Name                             531 non-null    object
 1   Region                                   317 non-null    object
 2   Province                                 218 non-null    object
 3   Deaths                                   531 non-null    int64
 4   Injuries                                 317 non-null    float64
 5   Affected                                 515 non-null    float64
 6   Houses destroyed                         530 non-null    float64
 7   Houses damaged                           531 non-null    int64
 8   Total Houses                             531 non-null    int64
 9   Damage to Infrastructure (PhP)           531 non-null    float64
 10  Damage to Agriculture + Fisheries (PhP)  531 non-null    float64
 11  Year                                     531 non-null    int64
 12  Category                                 531 non-null    object
dtypes: float64(5), int64(4), object(4)
memory usage: 54.1+ KB

In [9]:
df.isnull().any()

Cyclone Name                               False
Region                                      True
Province                                    True
Deaths                                     False
Injuries                                    True
Affected                                    True
Houses destroyed                            True
Houses damaged                             False
Total Houses                               False
Damage to Infrastructure (PhP)             False
Damage to Agriculture + Fisheries (PhP)    False
Year                                       False
Category                                   False
dtype: bool

## Step 3: Data cleaning (initial questions)

- Why are there missing values in the injuries and region columns?
- Why do categories differ before and after 2020?
- Why are some entries null for injuries, affected, etc.?
- Why is there a single missing value in houses destroyed?

### Check: Houses destroyed missing value

In [10]:
df[df['Houses destroyed'].isna()].head()

,Cyclone Name,Region,Province,Deaths,Injuries,Affected,Houses destroyed,Houses damaged,Total Houses,Damage to Infrastructure (PhP),Damage to Agriculture + Fisheries (PhP),Year,Category
293,Florita,CALABARZON,NaN,0,0.0,NaN,NaN,0,0,0.0,0.0,2022,Severe Tropical Storm

Finding: the missing value is a NaN in the source data.

### Step 3.1: Convert impact columns to integers

In [11]:
# Target columns
target_cols = ['Deaths', 'Injuries', 'Affected', 'Houses destroyed', 'Houses damaged', 'Total Houses']

# Fill missing values with 0. Assume no report = no injury
df_clean[target_cols] = df[target_cols].fillna(0)

# Round values
df_clean[target_cols] = df_clean[target_cols].round(0)

# Integer conversion
df_clean[target_cols] = df_clean[target_cols].astype(int)
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 531 entries, 0 to 530
Data columns (total 13 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Cyclone Name                             531 non-null    object
 1   Region                                   317 non-null    object
 2   Province                                 218 non-null    object
 3   Deaths                                   531 non-null    int64
 4   Injuries                                 531 non-null    int64
 5   Affected                                 531 non-null    int64
 6   Houses destroyed                         531 non-null    int64
 7   Houses damaged                           531 non-null    int64
 8   Total Houses                             531 non-null    int64
 9   Damage to Infrastructure (PhP)           531 non-null    float64
 10  Damage to Agriculture + Fisheries (PhP)  531 non-null    float64
 11  Year                                     531 non-null    int64
 12  Category                                 531 non-null    object
dtypes: float64(2), int64(7), object(4)
memory usage: 54.1+ KB

Result: impact and housing columns converted to integers.

In [12]:
df_clean.isnull().any()

Cyclone Name                               False
Region                                      True
Province                                    True
Deaths                                     False
Injuries                                   False
Affected                                   False
Houses destroyed                           False
Houses damaged                             False
Total Houses                               False
Damage to Infrastructure (PhP)             False
Damage to Agriculture + Fisheries (PhP)    False
Year                                       False
Category                                   False
dtype: bool

Result: no remaining nulls in injuries, affected, or housing columns.

### Step 3.2: Normalize typhoon classifications

In [13]:
df['Category'].value_counts()

Category
Very strong typhoon      105
Tropical Storm            65
Combined Effects          64
Super Typhoon             59
Severe Tropical Storm     47
Tropical Depression       44
Typhoon                   38
Strong typhoon            36
Violent typhoon           33
Tropical depression       23
Tropical storm            17
Name: count, dtype: int64

In [14]:
# Defining Mapping Dictionary
classification_map = {
    "Very strong typhoon": "Super Typhoon",
    "Violent typhoon": "Super Typhoon",
    "Super Typhoon": "Super Typhoon",
    "Strong typhoon": "Typhoon",
    "Typhoon": "Typhoon",
    "Severe Tropical Storm": "Severe Tropical Storm",
    "Tropical Storm": "Tropical Storm",
    "Tropical storm": "Tropical Storm",
    "Tropical Depression": "Tropical Depression",
    "Tropical depression": "Tropical Depression",
    "Combined Effects": "Combined Effects"
}

# Apply Mapping
df_clean['Category'] = df_clean['Category'].replace(classification_map)

# Final Check 
df_clean['Category'].value_counts()

Category
Super Typhoon            197
Tropical Storm            82
Typhoon                   74
Tropical Depression       67
Combined Effects          64
Severe Tropical Storm     47
Name: count, dtype: int64

In [15]:
df_clean.sample(5)

,Cyclone Name,Region,Province,Deaths,Injuries,Affected,Houses destroyed,Houses damaged,Total Houses,Damage to Infrastructure (PhP),Damage to Agriculture + Fisheries (PhP),Year,Category
63,Ursula,NaN,Occidental Mindoro,4,0,119037,4719,20240,24959,290860248.7,46224114.0,2019,Typhoon
118,Rolly,NaN,Metro Manila,0,0,20446,0,0,0,0.0,0.0,2020,Super Typhoon
60,Ursula,NaN,Iloilo,16,0,273971,5124,24846,29970,0.0,202503192.9,2019,Typhoon
453,Auring,Region 7,NaN,0,0,206,0,0,0,0.0,0.0,2025,Tropical Depression
481,Isang,CAR,NaN,0,0,9,0,1,1,0.0,0.0,2025,Tropical Storm

In [16]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 531 entries, 0 to 530
Data columns (total 13 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Cyclone Name                             531 non-null    object
 1   Region                                   317 non-null    object
 2   Province                                 218 non-null    object
 3   Deaths                                   531 non-null    int64
 4   Injuries                                 531 non-null    int64
 5   Affected                                 531 non-null    int64
 6   Houses destroyed                         531 non-null    int64
 7   Houses damaged                           531 non-null    int64
 8   Total Houses                             531 non-null    int64
 9   Damage to Infrastructure (PhP)           531 non-null    float64
 10  Damage to Agriculture + Fisheries (PhP)  531 non-null    float64
 11  Year                                     531 non-null    int64
 12  Category                                 531 non-null    object
dtypes: float64(2), int64(7), object(4)
memory usage: 54.1+ KB

### Step 3.3: Map provinces to regions

Use the external mapping and apply it to 2019-2020 entries only.

In [17]:
# Note: Code mapping provinces to region was obtained from an external dataset
# Region Mapping

regionNCR = ["Metro Manila"]
regionI = ["Ilocos Norte", "Ilocos Sur", "La Union", "Pangasinan"]
regionII = ["Batanes", "Cagayan", "Isabela", "Nueva Vizcaya", "Quirino"]
regionIII = ["Aurora", "Bataan", "Bulacan", "Nueva Ecija", "Pampanga", "Tarlac", "Zambales"]
regionIV_A = ["Batangas", "Cavite", "Laguna", "Quezon", "Rizal"]
regionMIMAROPA = ["Marinduque", "Occidental Mindoro", "Oriental Mindoro", "Palawan", "Romblon"]
regionV = ["Albay", "Camarines Norte", "Camarines Sur", "Catanduanes", "Masbate", "Sorsogon"]
regionVI = ["Aklan", "Antique", "Capiz", "Guimaras", "Iloilo", "Negros Occidental"]
regionVII = ["Bohol", "Cebu", "Negros Oriental", "Siquijor"]
regionVIII = ["Biliran", "Eastern Samar", "Leyte", "Northern Samar", "Samar", "Southern Leyte"]
regionIX = ["Zamboanga del Norte", "Zamboanga del Sur", "Zamboanga Sibugay"]
regionX = ["Bukidnon", "Camiguin", "Lanao del Norte", "Misamis Occidental", "Misamis Oriental"]
regionXI = ["Davao de Oro", "Davao del Oro", "Davao del Norte", "Davao del Sur", "Davao Occidental", "Davao Oriental"]
regionXII = ["Cotabato", "Sarangani", "South Cotabato", "Sultan Kudarat"]
regionXIII = ["Agusan del Norte", "Agusan del Sur", "Dinagat Islands", "Surigao del Norte", "Surigao del Sur"]
regionCAR = ["Abra", "Apayao", "Benguet", "Ifugao", "Kalinga", "Mountain Province"]
regionBARMM = ["Basilan", "Lanao del Sur", "Maguindanao", "Sulu", "Tawi-Tawi"]

# Mapping to dictionary
region_lists = {
    "NCR": regionNCR, "Region 1": regionI, "Region 2": regionII, 
    "Region 3": regionIII, "Region 4": regionIV_A, "MIMAROPA": regionMIMAROPA,
    "Region 5": regionV, "Region 6": regionVI, "Region 7": regionVII,
    "Region 8": regionVIII, "Region 9": regionIX, "Region 10": regionX,
    "Region 11": regionXI, "Region 12": regionXII, "Region 13": regionXIII,
    "CAR": regionCAR, "BARMM": regionBARMM
}

# Invert the dictionary: Map each Province to its Region
province_to_region = {
    province: region 
    for region, provinces in region_lists.items() 
    for province in provinces
}

# 1. Create a boolean mask for the target years
# This identifies exactly which rows we want to modify
year_mask = df_clean['Year'].isin([2019, 2020])

# 2. Apply the mapping ONLY to those rows
# .loc[rows, column] ensures we are writing to the original dataframe correctly
df_clean.loc[year_mask, 'Region'] = df_clean.loc[year_mask, 'Province'].map(province_to_region)
df_clean['Region'].value_counts()

Region
Region 3      59
Region 5      51
MIMAROPA      47
CAR           47
Region 2      43
Region 6      36
Region 8      34
Region 1      30
Region 4      23
CALABARZON    23
Region 7      21
Region 11     21
NCR           19
CARAGA        15
Region 13     14
Region 9      13
Region 12     13
Region 10     12
BARMM          9
NIR            1
Name: count, dtype: int64

In [18]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 531 entries, 0 to 530
Data columns (total 13 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Cyclone Name                             531 non-null    object
 1   Region                                   531 non-null    object
 2   Province                                 218 non-null    object
 3   Deaths                                   531 non-null    int64
 4   Injuries                                 531 non-null    int64
 5   Affected                                 531 non-null    int64
 6   Houses destroyed                         531 non-null    int64
 7   Houses damaged                           531 non-null    int64
 8   Total Houses                             531 non-null    int64
 9   Damage to Infrastructure (PhP)           531 non-null    float64
 10  Damage to Agriculture + Fisheries (PhP)  531 non-null    float64
 11  Year                                     531 non-null    int64
 12  Category                                 531 non-null    object
dtypes: float64(2), int64(7), object(4)
memory usage: 54.1+ KB

### Step 3.4: Drop province column

Keep region as the location field going forward.

In [19]:
df_clean.drop(columns=['Province'], inplace = True) # Modifies clean dataframe to drop provinces

In [20]:
df_clean.info() # Checking

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 531 entries, 0 to 530
Data columns (total 12 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Cyclone Name                             531 non-null    object
 1   Region                                   531 non-null    object
 2   Deaths                                   531 non-null    int64
 3   Injuries                                 531 non-null    int64
 4   Affected                                 531 non-null    int64
 5   Houses destroyed                         531 non-null    int64
 6   Houses damaged                           531 non-null    int64
 7   Total Houses                             531 non-null    int64
 8   Damage to Infrastructure (PhP)           531 non-null    float64
 9   Damage to Agriculture + Fisheries (PhP)  531 non-null    float64
 10  Year                                     531 non-null    int64
 11  Category                                 531 non-null    object
dtypes: float64(2), int64(7), object(3)
memory usage: 49.9+ KB

## Step 3.5: Region Formatting
This would aim to create consistency in formatting region row entries

In [21]:
region_lists = {
    "NCR": "NCR", "Region 1": "Region I", "Region 2": "Region II", 
    "Region 3": "Region III", "Region 4": "Region IV-A", "MIMAROPA": "Region IV-B",
    "Region 5": "Region V", "Region 6": "Region VI", "Region 7": "Region VII",
    "Region 8": "Region VIII", "Region 9": "Region IX", "Region 10": "Region X",
    "Region 11": "Region XI", "Region 12": "Region XII", "Region 13": "Region XIII",
    "CAR": "CAR", "BARMM": "BARMM"
}

df_clean['Region'] = df_clean['Region'].replace(region_lists)

In [22]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 531 entries, 0 to 530
Data columns (total 12 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Cyclone Name                             531 non-null    object
 1   Region                                   531 non-null    object
 2   Deaths                                   531 non-null    int64
 3   Injuries                                 531 non-null    int64
 4   Affected                                 531 non-null    int64
 5   Houses destroyed                         531 non-null    int64
 6   Houses damaged                           531 non-null    int64
 7   Total Houses                             531 non-null    int64
 8   Damage to Infrastructure (PhP)           531 non-null    float64
 9   Damage to Agriculture + Fisheries (PhP)  531 non-null    float64
 10  Year                                     531 non-null    int64
 11  Category                                 531 non-null    object
dtypes: float64(2), int64(7), object(3)
memory usage: 49.9+ KB

## Step 3.6: Region Merging
In the years 2019-2020, there appear to be multiple rows of the same region, representing each province before it was mapped into region. This section aims to add the stats of each region, so that it represents the true representation of a single region's stats.

In [23]:
df_clean.head(5)

,Cyclone Name,Region,Deaths,Injuries,Affected,Houses destroyed,Houses damaged,Total Houses,Damage to Infrastructure (PhP),Damage to Agriculture + Fisheries (PhP),Year,Category
0,Amang,Region XIII,0,0,10344,0,0,0,0.0,0.0,2019,Tropical Depression
1,Amang,Region XIII,0,0,3458,0,0,0,0.0,0.0,2019,Tropical Depression
2,Amang,Region XIII,0,0,1442,0,0,0,0.0,0.0,2019,Tropical Depression
3,Amang,Region XIII,0,0,853,0,0,0,0.0,0.0,2019,Tropical Depression
4,Amang,Region XIII,0,0,477,0,0,0,0.0,0.0,2019,Tropical Depression

In [24]:
df_clean.tail(5)

,Cyclone Name,Region,Deaths,Injuries,Affected,Houses destroyed,Houses damaged,Total Houses,Damage to Infrastructure (PhP),Damage to Agriculture + Fisheries (PhP),Year,Category
526,Verbena,Region VII,0,0,32308,4,204,208,0.0,0.0,2025,Tropical Depression
527,Verbena,Region VIII,0,0,1486,0,0,0,0.0,0.0,2025,Tropical Depression
528,Verbena,Region XIII,0,0,46923,6,0,6,0.0,0.0,2025,Tropical Depression
529,Verbena,CAR,0,0,335,0,19,19,18560.0,0.0,2025,Tropical Depression
530,Verbena,NCR,0,0,1691,0,0,0,0.0,0.0,2025,Tropical Depression

We use groupby on the columns, grouping them by cyclone, region, year, and category. Then, we use sum to add their numerical data together

In [25]:
# 1. Define the columns that identify the unique group
group_cols = ['Cyclone Name', 'Region', 'Year', 'Category']

# 2. Group by those columns, sum the numeric data, and reset the index
# We use numeric_only=True to ensure pandas only attempts to sum numbers
df_clean = df_clean.groupby(group_cols).sum(numeric_only=True).reset_index()

# 3. Arrange the DataFrame by Year then by Cyclone Name
df_clean = df_clean.sort_values(by=['Year', 'Cyclone Name'], ascending=[True, True])

# 4. View the result for 2019/2020 to verify the duplicates are gone
df_clean[df_clean['Year'].isin([2019, 2020])].head(10)

,Cyclone Name,Region,Year,Category,Deaths,Injuries,Affected,Houses destroyed,Houses damaged,Total Houses,Damage to Infrastructure (PhP),Damage to Agriculture + Fisheries (PhP)
19,Amang,Region XIII,2019,Tropical Depression,0,0,16574,0,0,0,0.0,0.0
69,Chedeng,Region XI,2019,Tropical Depression,0,0,6661,4,15,19,0.0,0.0
135,Falcon,CAR,2019,Tropical Storm,0,0,495,1,1,2,0.0,492320.0
136,Falcon,Region I,2019,Tropical Storm,0,0,5,0,1,1,914000000.0,0.0
137,Falcon,Region II,2019,Tropical Storm,0,0,502,0,0,0,118879500.0,36556039.0
243,Marilyn,Region II,2019,Tropical Depression,0,0,0,0,0,0,0.0,0.0
244,Marilyn,Region III,2019,Tropical Depression,0,0,0,0,0,0,0.0,0.0
245,Marilyn,Region IX,2019,Tropical Depression,0,0,8207,0,0,0,0.0,0.0
246,Marilyn,Region VI,2019,Tropical Depression,0,0,0,0,0,0,0.0,0.0
247,Marilyn,Region XI,2019,Tropical Depression,0,0,135,0,0,0,0.0,0.0

In [26]:
df_clean.head(5)

,Cyclone Name,Region,Year,Category,Deaths,Injuries,Affected,Houses destroyed,Houses damaged,Total Houses,Damage to Infrastructure (PhP),Damage to Agriculture + Fisheries (PhP)
19,Amang,Region XIII,2019,Tropical Depression,0,0,16574,0,0,0,0.0,0.0
69,Chedeng,Region XI,2019,Tropical Depression,0,0,6661,4,15,19,0.0,0.0
135,Falcon,CAR,2019,Tropical Storm,0,0,495,1,1,2,0.0,492320.0
136,Falcon,Region I,2019,Tropical Storm,0,0,5,0,1,1,914000000.0,0.0
137,Falcon,Region II,2019,Tropical Storm,0,0,502,0,0,0,118879500.0,36556039.0

In [27]:
df_clean.tail(5)

,Cyclone Name,Region,Year,Category,Deaths,Injuries,Affected,Houses destroyed,Houses damaged,Total Houses,Damage to Infrastructure (PhP),Damage to Agriculture + Fisheries (PhP)
377,Verbena,Region V,2025,Tropical Depression,0,0,10332,0,0,0,0.0,0.0
378,Verbena,Region VI,2025,Tropical Depression,0,0,8375,0,23,23,0.0,0.0
379,Verbena,Region VII,2025,Tropical Depression,0,0,32308,4,204,208,0.0,0.0
380,Verbena,Region VIII,2025,Tropical Depression,0,0,1486,0,0,0,0.0,0.0
381,Verbena,Region XIII,2025,Tropical Depression,0,0,46923,6,0,6,0.0,0.0

In [28]:
# Save your cleaned dataframe to a specific folder
# 'index=False' prevents pandas from adding an extra column of numbers at the start
df_clean.to_csv('../data/merged/cleaned_typhoon_impacts.csv', index=False)